### ISSUE TITLE
quotelink is followed by greentext

### ISSUE THREAD

**Issue by kaguy4** [hachikuji-san/koko-overboard#3]
posts that start with a quotelink followed by text on the same line get improperly greentext's
liek this:
```<blockquote class="comment"><span class="unkfunc"><a href="https://img.heyuri.net/b/koko.php?res=116416#p116429" class="quotelink">&gt;&gt;116429</a> test</span></blockquote>```

it's as expected on actual board:
![image](https://github.com/user-attachments/assets/72fad4c9-6a79-446f-84d0-679899b64a73)
it's like this on the overboard:
![image](https://github.com/user-attachments/assets/dc6f3dce-6f31-41c1-aa69-2af319ac31d3)

**Comment by hachikuji-san** [comment]
I'm not really sure how 2 fix this since i dont know what is causing it. I've looked into it before but didn't find anything it does differently in respect to how koko does it. Though if someone else is able to navigate my kuso code and find it then it would be a big help

**Comment by an0nc0w** [comment]
quote_unkfunc should come after quote_link, as it does in [koko](https://github.com/Heyuri/kokonotsuba/blob/ceda9b2a5742b47655d464066d961c340e116310/koko.php#L289)

```diff
diff --git a/overboard.php b/overboard.php
index 6b0e334..cd61ba3 100644
--- a/overboard.php
+++ b/overboard.php
@@ -164,8 +164,8 @@ function quote_link($comment, $dbBoardDetails){
 }
 
 function prepareComment($comment, $dbBoarDetails) {
-    $comment = quote_unkfunc($comment, $dbBoarDetails);
     $comment = quote_link($comment, $dbBoarDetails);
+    $comment = quote_unkfunc($comment, $dbBoarDetails);
     return $comment;
 }
 
```
